#include <stdlib.h>

char *n_keypad[11][11][6] = { {  {"A", NULL  },
  {"^<A", NULL  },
  {"^A", NULL  },
  {">^A", "^>A", NULL  },
  {"^^<A", "^<^A", NULL  },
  {"^^A", NULL  },
  {">^^A", "^^>A", NULL  },
  {"^^^<A", NULL  },
  {"^^^A", NULL  },
  {"^^^>A", ">^^^A", NULL  },
  {">A", NULL  },
 },
 {  {">vA", NULL  },
  {"A", NULL  },
  {">A", NULL  },
  {">>A", NULL  },
  {"^A", NULL  },
  {">^A", "^>A", NULL  },
  {">^>A", ">>^A", "^>>A", NULL  },
  {"^^A", NULL  },
  {">^^A", "^>^A", "^^>A", NULL  },
  {"^>^>A", "^^>>A", ">>^^A", "^>>^A", NULL  },
  {">>vA", ">v>A", NULL  },
 },
 {  {"vA", NULL  },
  {"<A", NULL  },
  {"A", NULL  },
  {">A", NULL  },
  {"^<A", "<^A", NULL  },
  {"^A", NULL  },
  {">^A", "^>A", NULL  },
  {"^^<A", "<^^A", "^<^A", NULL  },
  {"^^A", NULL  },
  {">^^A", "^>^A", "^^>A", NULL  },
  {"v>A", ">vA", NULL  },
 },
 {  {"v<A", "<vA", NULL  },
  {"<<A", NULL  },
  {"<A", NULL  },
  {"A", NULL  },
  {"<<^A", "^<<A", NULL  },
  {"^<A", "<^A", NULL  },
  {"^A", NULL  },
  {"^^<<A", "<<^^A", NULL  },
  {"^^<A", "<^^A", "^<^A", NULL  },
  {"^^A", NULL  },
  {"vA", NULL  },
 },
 {  {">vvA", "v>vA", NULL  },
  {"vA", NULL  },
  {"v>A", ">vA", NULL  },
  {">>vA", ">v>A", "v>>A", NULL  },
  {"A", NULL  },
  {">A", NULL  },
  {">>A", NULL  },
  {"^A", NULL  },
  {">^A", "^>A", NULL  },
  {">>^A", "^>>A", NULL  },
  {"v>v>A", "v>>vA", ">>vvA", NULL  },
 },
 {  {"vvA", NULL  },
  {"v<A", "<vA", NULL  },
  {"vA", NULL  },
  {"v>A", ">vA", NULL  },
  {"<A", NULL  },
  {"A", NULL  },
  {">A", NULL  },
  {"^<A", "<^A", NULL  },
  {"^A", NULL  },
  {">^A", "^>A", NULL  },
  {"vv>A", ">vvA", "v>vA", NULL  },
 },
 {  {"vv<A", "v<vA", "<vvA", NULL  },
  {"<<vA", "<v<A", "v<<A", NULL  },
  {"v<A", "<vA", NULL  },
  {"vA", NULL  },
  {"<<A", NULL  },
  {"<A", NULL  },
  {"A", NULL  },
  {"<<^A", "^<<A", "<^<A", NULL  },
  {"^<A", "<^A", NULL  },
  {"^A", NULL  },
  {"vvA", NULL  },
 },
 {  {">vvvA", "v>vvA", "vv>vA", NULL  },
  {"vvA", NULL  },
  {"vv>A", ">vvA", "v>vA", NULL  },
  {">>vvA", "vv>>A", NULL  },
  {"vA", NULL  },
  {"v>A", ">vA", NULL  },
  {">>vA", ">v>A", "v>>A", NULL  },
  {"A", NULL  },
  {">A", NULL  },
  {">>A", NULL  },
  {">>vvvA", "vv>>vA", "v>>vvA"  },
 },
 {  {"vvvA", NULL  },
  {"vv<A", "v<vA", "<vvA", NULL  },
  {"vvA", NULL  },
  {"vv>A", ">vvA", "v>vA", NULL  },
  {"v<A", "<vA", NULL  },
  {"vA", NULL  },
  {"v>A", ">vA", NULL  },
  {"<A", NULL  },
  {"A", NULL  },
  {">A", NULL  },
  {">vvvA", "v>vvA", "vv>vA", "vvv>A", NULL  },
 },
 {  {"<vvvA", "vvv<A", NULL  },
  {"vv<<A", "<<vvA", NULL  },
  {"vv<A", "v<vA", "<vvA", NULL  },
  {"vvA", NULL  },
  {"<<vA", "<v<A", "v<<A", NULL  },
  {"v<A", "<vA", NULL  },
  {"vA", NULL  },
  {"<<A", NULL  },
  {"<A", NULL  },
  {"A", NULL  },
  {"vvvA", NULL  },
 },
 {  {"<A", NULL  },
  {"<^<A", "^<<A", NULL  },
  {"^<A", "<^A", NULL  },
  {"^A", NULL  },
  {"<^<^A", "^^<<A", "<^^<A", NULL  },
  {"^^<A", "<^^A", "^<^A", NULL  },
  {"^^A", NULL  },
  {"<^^<^A", "<^^^<A", "^^^<<A", "<^<^^A", NULL },
  {"<^^^A", "^^^<A", NULL },
  {"^^^A", NULL  },
  {"A", NULL  },
 },
};


char *d_keypad[5][5][2] = { {  {"A", NULL  },
  {"vA", NULL  },
  {"v<A", NULL  },
  {"v>A", ">vA"  },
  {">A", NULL  },
 },
 {  {"^A", NULL  },
  {"A", NULL  },
  {"<A", NULL  },
  {">A", NULL  },
  {">^A", "^>A"  },
 },
 {  {">^A", NULL  },
  {">A", NULL  },
  {"A", NULL  },
  {">>A", NULL  },
  {">>^A", NULL  },
 },
 {  {"^<A", "<^A"  },
  {"<A", NULL  },
  {"<<A", NULL  },
  {"A", NULL  },
  {"^A", NULL  },
 },
 {  {"<A", NULL  },
  {"v<A", "<vA"  },
  {"<v<A", "v<<A"  },
  {"vA", NULL  },
  {"A", NULL  },
 },
};
